//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Usuarios_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Aplicacion
    {
        public Tb_Aplicacion()
        {
            this.Tb_Aplicacion_T = new HashSet<Tb_Aplicacion_T>();
            this.Tb_Grupo = new HashSet<Tb_Grupo>();
            this.Tb_Usuario_Aplicacion = new HashSet<Tb_Usuario_Aplicacion>();
        }
    
        public byte id_aplicacion { get; set; }
        public string codigo { get; set; }
        public Nullable<int> id_usuarioCreador { get; set; }
        public Nullable<int> id_usuarioModificador { get; set; }
        public bool activo { get; set; }
    
        public virtual ICollection<Tb_Aplicacion_T> Tb_Aplicacion_T { get; set; }
        public virtual ICollection<Tb_Grupo> Tb_Grupo { get; set; }
        public virtual ICollection<Tb_Usuario_Aplicacion> Tb_Usuario_Aplicacion { get; set; }
    }
}
