//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Usuarios_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Perfil
    {
        public Tb_Perfil()
        {
            this.Tb_Perfil_T = new HashSet<Tb_Perfil_T>();
            this.Tb_Usuario_Perfil = new HashSet<Tb_Usuario_Perfil>();
        }
    
        public byte id_perfil { get; set; }
        public string codigo { get; set; }
        public Nullable<int> id_usuarioCreador { get; set; }
        public Nullable<int> id_usuarioModificador { get; set; }
        public bool activo { get; set; }
    
        public virtual ICollection<Tb_Perfil_T> Tb_Perfil_T { get; set; }
        public virtual ICollection<Tb_Usuario_Perfil> Tb_Usuario_Perfil { get; set; }
    }
}
