//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Usuarios_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_TipoAuditoria_T
    {
        public byte id_tipoAuditoria_T { get; set; }
        public string tipoAuditoria { get; set; }
        public string descripcion { get; set; }
        public byte id_tipoAuditoria { get; set; }
        public byte id_idioma { get; set; }
        public bool activo { get; set; }
    
        public virtual Tb_TipoAuditoria Tb_TipoAuditoria { get; set; }
        public virtual Tb_Idioma Tb_Idioma { get; set; }
    }
}
