//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Usuarios_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Variable
    {
        public Tb_Variable()
        {
            this.Tb_Variable_T = new HashSet<Tb_Variable_T>();
            this.Tb_VariableSistema = new HashSet<Tb_VariableSistema>();
        }
    
        public byte id_variable { get; set; }
        public string codigo { get; set; }
        public Nullable<int> id_usuarioCreador { get; set; }
        public Nullable<int> id_usuarioModificador { get; set; }
        public bool activo { get; set; }
    
        public virtual ICollection<Tb_Variable_T> Tb_Variable_T { get; set; }
        public virtual ICollection<Tb_VariableSistema> Tb_VariableSistema { get; set; }
    }
}
