//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Usuarios_DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class UsuariosEntidades : DbContext
    {
        public UsuariosEntidades()
            : base("name=UsuariosEntidades")
        {
        }

        public UsuariosEntidades(string stringConnection)
            : base(stringConnection)
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tb_Aplicacion> Tb_Aplicacion { get; set; }
        public virtual DbSet<Tb_Aplicacion_T> Tb_Aplicacion_T { get; set; }
        public virtual DbSet<Tb_Contrasena> Tb_Contrasena { get; set; }
        public virtual DbSet<Tb_Grupo> Tb_Grupo { get; set; }
        public virtual DbSet<Tb_Perfil> Tb_Perfil { get; set; }
        public virtual DbSet<Tb_Perfil_T> Tb_Perfil_T { get; set; }
        public virtual DbSet<Tb_Sesion> Tb_Sesion { get; set; }
        public virtual DbSet<Tb_Usuario> Tb_Usuario { get; set; }
        public virtual DbSet<Tb_Usuario_Aplicacion> Tb_Usuario_Aplicacion { get; set; }
        public virtual DbSet<Tb_Usuario_Grupo> Tb_Usuario_Grupo { get; set; }
        public virtual DbSet<Tb_Usuario_Perfil> Tb_Usuario_Perfil { get; set; }
        public virtual DbSet<Tb_UsuarioActivo> Tb_UsuarioActivo { get; set; }
        public virtual DbSet<Tb_Variable> Tb_Variable { get; set; }
        public virtual DbSet<Tb_Variable_T> Tb_Variable_T { get; set; }
        public virtual DbSet<Tb_VariableSistema> Tb_VariableSistema { get; set; }
        public virtual DbSet<Tb_AuditoriaAplicacion> Tb_AuditoriaAplicacion { get; set; }
        public virtual DbSet<Tb_AuditoriaGrupo> Tb_AuditoriaGrupo { get; set; }
        public virtual DbSet<Tb_AuditoriaIdioma> Tb_AuditoriaIdioma { get; set; }
        public virtual DbSet<Tb_AuditoriaPerfil> Tb_AuditoriaPerfil { get; set; }
        public virtual DbSet<Tb_AuditoriaUsuario> Tb_AuditoriaUsuario { get; set; }
        public virtual DbSet<Tb_AuditoriaVariable> Tb_AuditoriaVariable { get; set; }
        public virtual DbSet<Tb_TipoAuditoria> Tb_TipoAuditoria { get; set; }
        public virtual DbSet<Tb_TipoAuditoria_T> Tb_TipoAuditoria_T { get; set; }
        public virtual DbSet<Tb_Idioma> Tb_Idioma { get; set; }
        public virtual DbSet<Tb_Idioma_T> Tb_Idioma_T { get; set; }
    
        public virtual int Sp_Aplicacion_Borrar(Nullable<int> id_usuarioBorrador, Nullable<int> id_aplicacion, ObjectParameter resultado)
        {
            var id_usuarioBorradorParameter = id_usuarioBorrador.HasValue ?
                new ObjectParameter("id_usuarioBorrador", id_usuarioBorrador) :
                new ObjectParameter("id_usuarioBorrador", typeof(int));
    
            var id_aplicacionParameter = id_aplicacion.HasValue ?
                new ObjectParameter("id_aplicacion", id_aplicacion) :
                new ObjectParameter("id_aplicacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_Aplicacion_Borrar", id_usuarioBorradorParameter, id_aplicacionParameter, resultado);
        }
    
        public virtual ObjectResult<Nullable<int>> Sp_Aplicacion_Crear(Nullable<int> id_usuarioCreador, string codigo, string aplicacion, string descripcion, ObjectParameter resultado)
        {
            var id_usuarioCreadorParameter = id_usuarioCreador.HasValue ?
                new ObjectParameter("id_usuarioCreador", id_usuarioCreador) :
                new ObjectParameter("id_usuarioCreador", typeof(int));
    
            var codigoParameter = codigo != null ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(string));
    
            var aplicacionParameter = aplicacion != null ?
                new ObjectParameter("aplicacion", aplicacion) :
                new ObjectParameter("aplicacion", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Sp_Aplicacion_Crear", id_usuarioCreadorParameter, codigoParameter, aplicacionParameter, descripcionParameter, resultado);
        }
    
        public virtual ObjectResult<Nullable<int>> Sp_Aplicacion_Modificar(Nullable<int> id_usuarioModificador, Nullable<int> id_idioma, Nullable<int> id_aplicacion, Nullable<int> id_aplicacion_t, string codigo, string aplicacion, string descripcion, Nullable<bool> activo, ObjectParameter resultado)
        {
            var id_usuarioModificadorParameter = id_usuarioModificador.HasValue ?
                new ObjectParameter("id_usuarioModificador", id_usuarioModificador) :
                new ObjectParameter("id_usuarioModificador", typeof(int));
    
            var id_idiomaParameter = id_idioma.HasValue ?
                new ObjectParameter("id_idioma", id_idioma) :
                new ObjectParameter("id_idioma", typeof(int));
    
            var id_aplicacionParameter = id_aplicacion.HasValue ?
                new ObjectParameter("id_aplicacion", id_aplicacion) :
                new ObjectParameter("id_aplicacion", typeof(int));
    
            var id_aplicacion_tParameter = id_aplicacion_t.HasValue ?
                new ObjectParameter("id_aplicacion_t", id_aplicacion_t) :
                new ObjectParameter("id_aplicacion_t", typeof(int));
    
            var codigoParameter = codigo != null ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(string));
    
            var aplicacionParameter = aplicacion != null ?
                new ObjectParameter("aplicacion", aplicacion) :
                new ObjectParameter("aplicacion", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            var activoParameter = activo.HasValue ?
                new ObjectParameter("activo", activo) :
                new ObjectParameter("activo", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Sp_Aplicacion_Modificar", id_usuarioModificadorParameter, id_idiomaParameter, id_aplicacionParameter, id_aplicacion_tParameter, codigoParameter, aplicacionParameter, descripcionParameter, activoParameter, resultado);
        }
    
        public virtual int Sp_Grupo_Borrar(Nullable<int> id_usuarioBorrador, Nullable<int> id_grupo, ObjectParameter resultado)
        {
            var id_usuarioBorradorParameter = id_usuarioBorrador.HasValue ?
                new ObjectParameter("id_usuarioBorrador", id_usuarioBorrador) :
                new ObjectParameter("id_usuarioBorrador", typeof(int));
    
            var id_grupoParameter = id_grupo.HasValue ?
                new ObjectParameter("id_grupo", id_grupo) :
                new ObjectParameter("id_grupo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_Grupo_Borrar", id_usuarioBorradorParameter, id_grupoParameter, resultado);
        }
    
        public virtual ObjectResult<Nullable<int>> Sp_Grupo_Crear(Nullable<int> id_usuarioCreador, Nullable<int> id_aplicacion, string codigo, string grupo, string descripcion, ObjectParameter resultado)
        {
            var id_usuarioCreadorParameter = id_usuarioCreador.HasValue ?
                new ObjectParameter("id_usuarioCreador", id_usuarioCreador) :
                new ObjectParameter("id_usuarioCreador", typeof(int));
    
            var id_aplicacionParameter = id_aplicacion.HasValue ?
                new ObjectParameter("id_aplicacion", id_aplicacion) :
                new ObjectParameter("id_aplicacion", typeof(int));
    
            var codigoParameter = codigo != null ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(string));
    
            var grupoParameter = grupo != null ?
                new ObjectParameter("grupo", grupo) :
                new ObjectParameter("grupo", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Sp_Grupo_Crear", id_usuarioCreadorParameter, id_aplicacionParameter, codigoParameter, grupoParameter, descripcionParameter, resultado);
        }
    
        public virtual ObjectResult<Nullable<int>> Sp_Grupo_Modificar(Nullable<int> id_usuarioModificador, Nullable<int> id_grupo, string codigo, string grupo, string descripcion, Nullable<bool> activo, ObjectParameter resultado)
        {
            var id_usuarioModificadorParameter = id_usuarioModificador.HasValue ?
                new ObjectParameter("id_usuarioModificador", id_usuarioModificador) :
                new ObjectParameter("id_usuarioModificador", typeof(int));
    
            var id_grupoParameter = id_grupo.HasValue ?
                new ObjectParameter("id_grupo", id_grupo) :
                new ObjectParameter("id_grupo", typeof(int));
    
            var codigoParameter = codigo != null ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(string));
    
            var grupoParameter = grupo != null ?
                new ObjectParameter("grupo", grupo) :
                new ObjectParameter("grupo", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            var activoParameter = activo.HasValue ?
                new ObjectParameter("activo", activo) :
                new ObjectParameter("activo", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Sp_Grupo_Modificar", id_usuarioModificadorParameter, id_grupoParameter, codigoParameter, grupoParameter, descripcionParameter, activoParameter, resultado);
        }
    
        public virtual int Sp_Perfil_Borrar(Nullable<int> id_usuarioBorrador, Nullable<int> id_perfil, ObjectParameter resultado)
        {
            var id_usuarioBorradorParameter = id_usuarioBorrador.HasValue ?
                new ObjectParameter("id_usuarioBorrador", id_usuarioBorrador) :
                new ObjectParameter("id_usuarioBorrador", typeof(int));
    
            var id_perfilParameter = id_perfil.HasValue ?
                new ObjectParameter("id_perfil", id_perfil) :
                new ObjectParameter("id_perfil", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_Perfil_Borrar", id_usuarioBorradorParameter, id_perfilParameter, resultado);
        }
    
        public virtual ObjectResult<Nullable<int>> Sp_Perfil_Crear(Nullable<int> id_usuarioCreador, string codigo, string perfil, string descripcion, ObjectParameter resultado)
        {
            var id_usuarioCreadorParameter = id_usuarioCreador.HasValue ?
                new ObjectParameter("id_usuarioCreador", id_usuarioCreador) :
                new ObjectParameter("id_usuarioCreador", typeof(int));
    
            var codigoParameter = codigo != null ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(string));
    
            var perfilParameter = perfil != null ?
                new ObjectParameter("perfil", perfil) :
                new ObjectParameter("perfil", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Sp_Perfil_Crear", id_usuarioCreadorParameter, codigoParameter, perfilParameter, descripcionParameter, resultado);
        }
    
        public virtual ObjectResult<Nullable<int>> Sp_Perfil_Modificar(Nullable<int> id_usuarioModificador, Nullable<int> id_idioma, Nullable<int> id_perfil, Nullable<int> id_perfil_t, string codigo, string perfil, string descripcion, Nullable<bool> activo, ObjectParameter resultado)
        {
            var id_usuarioModificadorParameter = id_usuarioModificador.HasValue ?
                new ObjectParameter("id_usuarioModificador", id_usuarioModificador) :
                new ObjectParameter("id_usuarioModificador", typeof(int));
    
            var id_idiomaParameter = id_idioma.HasValue ?
                new ObjectParameter("id_idioma", id_idioma) :
                new ObjectParameter("id_idioma", typeof(int));
    
            var id_perfilParameter = id_perfil.HasValue ?
                new ObjectParameter("id_perfil", id_perfil) :
                new ObjectParameter("id_perfil", typeof(int));
    
            var id_perfil_tParameter = id_perfil_t.HasValue ?
                new ObjectParameter("id_perfil_t", id_perfil_t) :
                new ObjectParameter("id_perfil_t", typeof(int));
    
            var codigoParameter = codigo != null ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(string));
    
            var perfilParameter = perfil != null ?
                new ObjectParameter("perfil", perfil) :
                new ObjectParameter("perfil", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            var activoParameter = activo.HasValue ?
                new ObjectParameter("activo", activo) :
                new ObjectParameter("activo", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Sp_Perfil_Modificar", id_usuarioModificadorParameter, id_idiomaParameter, id_perfilParameter, id_perfil_tParameter, codigoParameter, perfilParameter, descripcionParameter, activoParameter, resultado);
        }
    
        public virtual int Sp_Usuario_Aplicacion_Borrar(Nullable<int> id_usuarioBorrador, Nullable<int> id_usuarioAplicacion, ObjectParameter resultado)
        {
            var id_usuarioBorradorParameter = id_usuarioBorrador.HasValue ?
                new ObjectParameter("id_usuarioBorrador", id_usuarioBorrador) :
                new ObjectParameter("id_usuarioBorrador", typeof(int));
    
            var id_usuarioAplicacionParameter = id_usuarioAplicacion.HasValue ?
                new ObjectParameter("id_usuarioAplicacion", id_usuarioAplicacion) :
                new ObjectParameter("id_usuarioAplicacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_Usuario_Aplicacion_Borrar", id_usuarioBorradorParameter, id_usuarioAplicacionParameter, resultado);
        }
    
        public virtual ObjectResult<Nullable<int>> Sp_Usuario_Aplicacion_Crear(Nullable<int> id_usuarioCreador, Nullable<int> id_usuario, Nullable<int> id_aplicacion, ObjectParameter resultado)
        {
            var id_usuarioCreadorParameter = id_usuarioCreador.HasValue ?
                new ObjectParameter("id_usuarioCreador", id_usuarioCreador) :
                new ObjectParameter("id_usuarioCreador", typeof(int));
    
            var id_usuarioParameter = id_usuario.HasValue ?
                new ObjectParameter("id_usuario", id_usuario) :
                new ObjectParameter("id_usuario", typeof(int));
    
            var id_aplicacionParameter = id_aplicacion.HasValue ?
                new ObjectParameter("id_aplicacion", id_aplicacion) :
                new ObjectParameter("id_aplicacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Sp_Usuario_Aplicacion_Crear", id_usuarioCreadorParameter, id_usuarioParameter, id_aplicacionParameter, resultado);
        }
    
        public virtual ObjectResult<Nullable<int>> Sp_Usuario_Aplicacion_Modificar(Nullable<int> id_usuarioModificador, Nullable<int> id_usuarioAplicacion, Nullable<int> id_usuario, Nullable<int> id_aplicacion, Nullable<bool> activo, ObjectParameter resultado)
        {
            var id_usuarioModificadorParameter = id_usuarioModificador.HasValue ?
                new ObjectParameter("id_usuarioModificador", id_usuarioModificador) :
                new ObjectParameter("id_usuarioModificador", typeof(int));
    
            var id_usuarioAplicacionParameter = id_usuarioAplicacion.HasValue ?
                new ObjectParameter("id_usuarioAplicacion", id_usuarioAplicacion) :
                new ObjectParameter("id_usuarioAplicacion", typeof(int));
    
            var id_usuarioParameter = id_usuario.HasValue ?
                new ObjectParameter("id_usuario", id_usuario) :
                new ObjectParameter("id_usuario", typeof(int));
    
            var id_aplicacionParameter = id_aplicacion.HasValue ?
                new ObjectParameter("id_aplicacion", id_aplicacion) :
                new ObjectParameter("id_aplicacion", typeof(int));
    
            var activoParameter = activo.HasValue ?
                new ObjectParameter("activo", activo) :
                new ObjectParameter("activo", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Sp_Usuario_Aplicacion_Modificar", id_usuarioModificadorParameter, id_usuarioAplicacionParameter, id_usuarioParameter, id_aplicacionParameter, activoParameter, resultado);
        }
    
        public virtual ObjectResult<Nullable<int>> Sp_Usuario_Borrar(Nullable<int> id_usuarioBorrador, Nullable<int> id_usuario, ObjectParameter resultado)
        {
            var id_usuarioBorradorParameter = id_usuarioBorrador.HasValue ?
                new ObjectParameter("id_usuarioBorrador", id_usuarioBorrador) :
                new ObjectParameter("id_usuarioBorrador", typeof(int));
    
            var id_usuarioParameter = id_usuario.HasValue ?
                new ObjectParameter("id_usuario", id_usuario) :
                new ObjectParameter("id_usuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Sp_Usuario_Borrar", id_usuarioBorradorParameter, id_usuarioParameter, resultado);
        }
    
        public virtual ObjectResult<Nullable<int>> Sp_Usuario_Crear(Nullable<int> id_usuarioCreador, string usuario, string usuario_, string usuarioCorreo, string usuarioCorreo_, string contrasena, Nullable<bool> activo, ObjectParameter resultado)
        {
            var id_usuarioCreadorParameter = id_usuarioCreador.HasValue ?
                new ObjectParameter("id_usuarioCreador", id_usuarioCreador) :
                new ObjectParameter("id_usuarioCreador", typeof(int));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            var usuario_Parameter = usuario_ != null ?
                new ObjectParameter("usuario_", usuario_) :
                new ObjectParameter("usuario_", typeof(string));
    
            var usuarioCorreoParameter = usuarioCorreo != null ?
                new ObjectParameter("usuarioCorreo", usuarioCorreo) :
                new ObjectParameter("usuarioCorreo", typeof(string));
    
            var usuarioCorreo_Parameter = usuarioCorreo_ != null ?
                new ObjectParameter("usuarioCorreo_", usuarioCorreo_) :
                new ObjectParameter("usuarioCorreo_", typeof(string));
    
            var contrasenaParameter = contrasena != null ?
                new ObjectParameter("contrasena", contrasena) :
                new ObjectParameter("contrasena", typeof(string));
    
            var activoParameter = activo.HasValue ?
                new ObjectParameter("activo", activo) :
                new ObjectParameter("activo", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Sp_Usuario_Crear", id_usuarioCreadorParameter, usuarioParameter, usuario_Parameter, usuarioCorreoParameter, usuarioCorreo_Parameter, contrasenaParameter, activoParameter, resultado);
        }
    
        public virtual int Sp_Usuario_Grupo_Borrar(Nullable<int> id_usuarioBorrador, Nullable<int> id_usuarioGrupo, ObjectParameter resultado)
        {
            var id_usuarioBorradorParameter = id_usuarioBorrador.HasValue ?
                new ObjectParameter("id_usuarioBorrador", id_usuarioBorrador) :
                new ObjectParameter("id_usuarioBorrador", typeof(int));
    
            var id_usuarioGrupoParameter = id_usuarioGrupo.HasValue ?
                new ObjectParameter("id_usuarioGrupo", id_usuarioGrupo) :
                new ObjectParameter("id_usuarioGrupo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_Usuario_Grupo_Borrar", id_usuarioBorradorParameter, id_usuarioGrupoParameter, resultado);
        }
    
        public virtual ObjectResult<Nullable<int>> Sp_Usuario_Grupo_Crear(Nullable<int> id_usuarioCreador, Nullable<int> id_usuario, Nullable<int> id_grupo, ObjectParameter resultado)
        {
            var id_usuarioCreadorParameter = id_usuarioCreador.HasValue ?
                new ObjectParameter("id_usuarioCreador", id_usuarioCreador) :
                new ObjectParameter("id_usuarioCreador", typeof(int));
    
            var id_usuarioParameter = id_usuario.HasValue ?
                new ObjectParameter("id_usuario", id_usuario) :
                new ObjectParameter("id_usuario", typeof(int));
    
            var id_grupoParameter = id_grupo.HasValue ?
                new ObjectParameter("id_grupo", id_grupo) :
                new ObjectParameter("id_grupo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Sp_Usuario_Grupo_Crear", id_usuarioCreadorParameter, id_usuarioParameter, id_grupoParameter, resultado);
        }
    
        public virtual ObjectResult<Nullable<int>> Sp_Usuario_Grupo_Modificar(Nullable<int> id_usuarioModificador, Nullable<int> id_usuarioGrupo, Nullable<int> id_usuario, Nullable<int> id_grupo, Nullable<bool> activo, ObjectParameter resultado)
        {
            var id_usuarioModificadorParameter = id_usuarioModificador.HasValue ?
                new ObjectParameter("id_usuarioModificador", id_usuarioModificador) :
                new ObjectParameter("id_usuarioModificador", typeof(int));
    
            var id_usuarioGrupoParameter = id_usuarioGrupo.HasValue ?
                new ObjectParameter("id_usuarioGrupo", id_usuarioGrupo) :
                new ObjectParameter("id_usuarioGrupo", typeof(int));
    
            var id_usuarioParameter = id_usuario.HasValue ?
                new ObjectParameter("id_usuario", id_usuario) :
                new ObjectParameter("id_usuario", typeof(int));
    
            var id_grupoParameter = id_grupo.HasValue ?
                new ObjectParameter("id_grupo", id_grupo) :
                new ObjectParameter("id_grupo", typeof(int));
    
            var activoParameter = activo.HasValue ?
                new ObjectParameter("activo", activo) :
                new ObjectParameter("activo", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Sp_Usuario_Grupo_Modificar", id_usuarioModificadorParameter, id_usuarioGrupoParameter, id_usuarioParameter, id_grupoParameter, activoParameter, resultado);
        }
    
        public virtual ObjectResult<Nullable<int>> Sp_Usuario_Modificar(Nullable<int> id_usuarioModificador, Nullable<int> id_usuario, string usuario, string usuario_, string usuarioCorreo, string usuarioCorreo_, string contrasena, Nullable<bool> activo, ObjectParameter resultado)
        {
            var id_usuarioModificadorParameter = id_usuarioModificador.HasValue ?
                new ObjectParameter("id_usuarioModificador", id_usuarioModificador) :
                new ObjectParameter("id_usuarioModificador", typeof(int));
    
            var id_usuarioParameter = id_usuario.HasValue ?
                new ObjectParameter("id_usuario", id_usuario) :
                new ObjectParameter("id_usuario", typeof(int));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            var usuario_Parameter = usuario_ != null ?
                new ObjectParameter("usuario_", usuario_) :
                new ObjectParameter("usuario_", typeof(string));
    
            var usuarioCorreoParameter = usuarioCorreo != null ?
                new ObjectParameter("usuarioCorreo", usuarioCorreo) :
                new ObjectParameter("usuarioCorreo", typeof(string));
    
            var usuarioCorreo_Parameter = usuarioCorreo_ != null ?
                new ObjectParameter("usuarioCorreo_", usuarioCorreo_) :
                new ObjectParameter("usuarioCorreo_", typeof(string));
    
            var contrasenaParameter = contrasena != null ?
                new ObjectParameter("contrasena", contrasena) :
                new ObjectParameter("contrasena", typeof(string));
    
            var activoParameter = activo.HasValue ?
                new ObjectParameter("activo", activo) :
                new ObjectParameter("activo", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Sp_Usuario_Modificar", id_usuarioModificadorParameter, id_usuarioParameter, usuarioParameter, usuario_Parameter, usuarioCorreoParameter, usuarioCorreo_Parameter, contrasenaParameter, activoParameter, resultado);
        }
    
        public virtual int Sp_Usuario_Perfil_Borrar(Nullable<int> id_usuarioBorrador, Nullable<int> id_usuarioPerfil, ObjectParameter resultado)
        {
            var id_usuarioBorradorParameter = id_usuarioBorrador.HasValue ?
                new ObjectParameter("id_usuarioBorrador", id_usuarioBorrador) :
                new ObjectParameter("id_usuarioBorrador", typeof(int));
    
            var id_usuarioPerfilParameter = id_usuarioPerfil.HasValue ?
                new ObjectParameter("id_usuarioPerfil", id_usuarioPerfil) :
                new ObjectParameter("id_usuarioPerfil", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_Usuario_Perfil_Borrar", id_usuarioBorradorParameter, id_usuarioPerfilParameter, resultado);
        }
    
        public virtual ObjectResult<Nullable<int>> Sp_Usuario_Perfil_Crear(Nullable<int> id_usuarioCreador, Nullable<int> id_usuario, Nullable<int> id_perfil, ObjectParameter resultado)
        {
            var id_usuarioCreadorParameter = id_usuarioCreador.HasValue ?
                new ObjectParameter("id_usuarioCreador", id_usuarioCreador) :
                new ObjectParameter("id_usuarioCreador", typeof(int));
    
            var id_usuarioParameter = id_usuario.HasValue ?
                new ObjectParameter("id_usuario", id_usuario) :
                new ObjectParameter("id_usuario", typeof(int));
    
            var id_perfilParameter = id_perfil.HasValue ?
                new ObjectParameter("id_perfil", id_perfil) :
                new ObjectParameter("id_perfil", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Sp_Usuario_Perfil_Crear", id_usuarioCreadorParameter, id_usuarioParameter, id_perfilParameter, resultado);
        }
    
        public virtual ObjectResult<Nullable<int>> Sp_Usuario_Perfil_Modificar(Nullable<int> id_usuarioPerfil, Nullable<int> id_usuario, Nullable<int> id_perfil, Nullable<int> id_usuarioModificador, ObjectParameter resultado)
        {
            var id_usuarioPerfilParameter = id_usuarioPerfil.HasValue ?
                new ObjectParameter("id_usuarioPerfil", id_usuarioPerfil) :
                new ObjectParameter("id_usuarioPerfil", typeof(int));
    
            var id_usuarioParameter = id_usuario.HasValue ?
                new ObjectParameter("id_usuario", id_usuario) :
                new ObjectParameter("id_usuario", typeof(int));
    
            var id_perfilParameter = id_perfil.HasValue ?
                new ObjectParameter("id_perfil", id_perfil) :
                new ObjectParameter("id_perfil", typeof(int));
    
            var id_usuarioModificadorParameter = id_usuarioModificador.HasValue ?
                new ObjectParameter("id_usuarioModificador", id_usuarioModificador) :
                new ObjectParameter("id_usuarioModificador", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Sp_Usuario_Perfil_Modificar", id_usuarioPerfilParameter, id_usuarioParameter, id_perfilParameter, id_usuarioModificadorParameter, resultado);
        }
    
        public virtual ObjectResult<Nullable<int>> Sp_UsuarioAdmin_Crear(string usuario, string usuario_, string contrasena, ObjectParameter resultado)
        {
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            var usuario_Parameter = usuario_ != null ?
                new ObjectParameter("usuario_", usuario_) :
                new ObjectParameter("usuario_", typeof(string));
    
            var contrasenaParameter = contrasena != null ?
                new ObjectParameter("contrasena", contrasena) :
                new ObjectParameter("contrasena", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Sp_UsuarioAdmin_Crear", usuarioParameter, usuario_Parameter, contrasenaParameter, resultado);
        }
    
        public virtual int Sp_Variable_Borrar(Nullable<int> id_usuarioBorrador, Nullable<int> id_variable, ObjectParameter resultado)
        {
            var id_usuarioBorradorParameter = id_usuarioBorrador.HasValue ?
                new ObjectParameter("id_usuarioBorrador", id_usuarioBorrador) :
                new ObjectParameter("id_usuarioBorrador", typeof(int));
    
            var id_variableParameter = id_variable.HasValue ?
                new ObjectParameter("id_variable", id_variable) :
                new ObjectParameter("id_variable", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_Variable_Borrar", id_usuarioBorradorParameter, id_variableParameter, resultado);
        }
    
        public virtual ObjectResult<Nullable<int>> Sp_Variable_Crear(Nullable<int> id_usuarioCreador, string codigo, string variable, string descripcion, ObjectParameter resultado)
        {
            var id_usuarioCreadorParameter = id_usuarioCreador.HasValue ?
                new ObjectParameter("id_usuarioCreador", id_usuarioCreador) :
                new ObjectParameter("id_usuarioCreador", typeof(int));
    
            var codigoParameter = codigo != null ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(string));
    
            var variableParameter = variable != null ?
                new ObjectParameter("variable", variable) :
                new ObjectParameter("variable", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Sp_Variable_Crear", id_usuarioCreadorParameter, codigoParameter, variableParameter, descripcionParameter, resultado);
        }
    
        public virtual ObjectResult<Nullable<int>> Sp_Variable_Modificar(Nullable<int> id_usuarioModificador, Nullable<int> id_idioma, Nullable<int> id_variable, Nullable<int> id_variable_t, string codigo, string variable, string descripcion, Nullable<bool> activo, ObjectParameter resultado)
        {
            var id_usuarioModificadorParameter = id_usuarioModificador.HasValue ?
                new ObjectParameter("id_usuarioModificador", id_usuarioModificador) :
                new ObjectParameter("id_usuarioModificador", typeof(int));
    
            var id_idiomaParameter = id_idioma.HasValue ?
                new ObjectParameter("id_idioma", id_idioma) :
                new ObjectParameter("id_idioma", typeof(int));
    
            var id_variableParameter = id_variable.HasValue ?
                new ObjectParameter("id_variable", id_variable) :
                new ObjectParameter("id_variable", typeof(int));
    
            var id_variable_tParameter = id_variable_t.HasValue ?
                new ObjectParameter("id_variable_t", id_variable_t) :
                new ObjectParameter("id_variable_t", typeof(int));
    
            var codigoParameter = codigo != null ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(string));
    
            var variableParameter = variable != null ?
                new ObjectParameter("variable", variable) :
                new ObjectParameter("variable", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            var activoParameter = activo.HasValue ?
                new ObjectParameter("activo", activo) :
                new ObjectParameter("activo", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Sp_Variable_Modificar", id_usuarioModificadorParameter, id_idiomaParameter, id_variableParameter, id_variable_tParameter, codigoParameter, variableParameter, descripcionParameter, activoParameter, resultado);
        }
    
        public virtual int Sp_VariableSistema_Borrar(Nullable<int> id_usuarioBorrador, Nullable<int> id_variableSistema, ObjectParameter resultado)
        {
            var id_usuarioBorradorParameter = id_usuarioBorrador.HasValue ?
                new ObjectParameter("id_usuarioBorrador", id_usuarioBorrador) :
                new ObjectParameter("id_usuarioBorrador", typeof(int));
    
            var id_variableSistemaParameter = id_variableSistema.HasValue ?
                new ObjectParameter("id_variableSistema", id_variableSistema) :
                new ObjectParameter("id_variableSistema", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_VariableSistema_Borrar", id_usuarioBorradorParameter, id_variableSistemaParameter, resultado);
        }
    
        public virtual ObjectResult<Nullable<int>> Sp_VariableSistema_Crear(Nullable<int> id_usuarioCreador, Nullable<int> id_variable, string valor, ObjectParameter resultado)
        {
            var id_usuarioCreadorParameter = id_usuarioCreador.HasValue ?
                new ObjectParameter("id_usuarioCreador", id_usuarioCreador) :
                new ObjectParameter("id_usuarioCreador", typeof(int));
    
            var id_variableParameter = id_variable.HasValue ?
                new ObjectParameter("id_variable", id_variable) :
                new ObjectParameter("id_variable", typeof(int));
    
            var valorParameter = valor != null ?
                new ObjectParameter("valor", valor) :
                new ObjectParameter("valor", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Sp_VariableSistema_Crear", id_usuarioCreadorParameter, id_variableParameter, valorParameter, resultado);
        }
    
        public virtual ObjectResult<Nullable<int>> Sp_VariableSistema_Modificar(Nullable<int> id_usuarioModificador, Nullable<int> id_variableSistema, string valor, Nullable<bool> activo, ObjectParameter resultado)
        {
            var id_usuarioModificadorParameter = id_usuarioModificador.HasValue ?
                new ObjectParameter("id_usuarioModificador", id_usuarioModificador) :
                new ObjectParameter("id_usuarioModificador", typeof(int));
    
            var id_variableSistemaParameter = id_variableSistema.HasValue ?
                new ObjectParameter("id_variableSistema", id_variableSistema) :
                new ObjectParameter("id_variableSistema", typeof(int));
    
            var valorParameter = valor != null ?
                new ObjectParameter("valor", valor) :
                new ObjectParameter("valor", typeof(string));
    
            var activoParameter = activo.HasValue ?
                new ObjectParameter("activo", activo) :
                new ObjectParameter("activo", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Sp_VariableSistema_Modificar", id_usuarioModificadorParameter, id_variableSistemaParameter, valorParameter, activoParameter, resultado);
        }
    
        public virtual int Sp_Idioma_Borrar(Nullable<int> id_usuarioBorrador, Nullable<int> id_idioma, ObjectParameter resultado)
        {
            var id_usuarioBorradorParameter = id_usuarioBorrador.HasValue ?
                new ObjectParameter("id_usuarioBorrador", id_usuarioBorrador) :
                new ObjectParameter("id_usuarioBorrador", typeof(int));
    
            var id_idiomaParameter = id_idioma.HasValue ?
                new ObjectParameter("id_idioma", id_idioma) :
                new ObjectParameter("id_idioma", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_Idioma_Borrar", id_usuarioBorradorParameter, id_idiomaParameter, resultado);
        }
    
        public virtual ObjectResult<Nullable<int>> Sp_Idioma_Crear(Nullable<int> id_usuarioCreador, string codigo, string idioma, string descripcion, ObjectParameter resultado)
        {
            var id_usuarioCreadorParameter = id_usuarioCreador.HasValue ?
                new ObjectParameter("id_usuarioCreador", id_usuarioCreador) :
                new ObjectParameter("id_usuarioCreador", typeof(int));
    
            var codigoParameter = codigo != null ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(string));
    
            var idiomaParameter = idioma != null ?
                new ObjectParameter("idioma", idioma) :
                new ObjectParameter("idioma", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Sp_Idioma_Crear", id_usuarioCreadorParameter, codigoParameter, idiomaParameter, descripcionParameter, resultado);
        }
    
        public virtual ObjectResult<Nullable<int>> Sp_Idioma_Modificar(Nullable<int> id_usuarioModificador, Nullable<int> id_idioma, Nullable<int> id_idioma_t, string codigo, string idioma, Nullable<bool> activo, ObjectParameter resultado)
        {
            var id_usuarioModificadorParameter = id_usuarioModificador.HasValue ?
                new ObjectParameter("id_usuarioModificador", id_usuarioModificador) :
                new ObjectParameter("id_usuarioModificador", typeof(int));
    
            var id_idiomaParameter = id_idioma.HasValue ?
                new ObjectParameter("id_idioma", id_idioma) :
                new ObjectParameter("id_idioma", typeof(int));
    
            var id_idioma_tParameter = id_idioma_t.HasValue ?
                new ObjectParameter("id_idioma_t", id_idioma_t) :
                new ObjectParameter("id_idioma_t", typeof(int));
    
            var codigoParameter = codigo != null ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(string));
    
            var idiomaParameter = idioma != null ?
                new ObjectParameter("idioma", idioma) :
                new ObjectParameter("idioma", typeof(string));
    
            var activoParameter = activo.HasValue ?
                new ObjectParameter("activo", activo) :
                new ObjectParameter("activo", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Sp_Idioma_Modificar", id_usuarioModificadorParameter, id_idiomaParameter, id_idioma_tParameter, codigoParameter, idiomaParameter, activoParameter, resultado);
        }
    
        public virtual ObjectResult<Nullable<int>> Sp_Usuario_Autenticar(string usuario, string contrasena, ObjectParameter resultado)
        {
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            var contrasenaParameter = contrasena != null ?
                new ObjectParameter("contrasena", contrasena) :
                new ObjectParameter("contrasena", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Sp_Usuario_Autenticar", usuarioParameter, contrasenaParameter, resultado);
        }
    
        public virtual ObjectResult<Nullable<int>> Sp_Usuario_Reautenticar(string sesion, ObjectParameter resultado)
        {
            var sesionParameter = sesion != null ?
                new ObjectParameter("sesion", sesion) :
                new ObjectParameter("sesion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Sp_Usuario_Reautenticar", sesionParameter, resultado);
        }
    }
}
